### ISSUE TITLE
Build User Interface (Streamlit)

### ISSUE THREAD

**Issue by rkemp101** [dicanadu/01-household-energy#10]
### Create user interface:
- Minimal input: square feet, persons in the house
- Minimal output: KWH

### Additional options: 
- U.S. map

### TODO
- [x] move area to start page 
- [x] bathrooms - hardcode half as 0
- [x] get rid of Non applicables (they are 0) and Don't Knows
- [x] laptops impute to 0, only computer total
- [x] light bulbs: impute two to 0 and only have one field
- [x] mv telework to household characteristics
- [x] add sensible defaluts

**Comment by rkemp101** [comment]
This is the Proof of Concept (POC)

[https://www.whatnextnow.com/home/solar/power-consumption-calculator](https://github.com/users/dicanadu/projects/1/views/url)

**Comment by slebedeva** [comment]
Smaller comments:

- change sliders into number input to accommodate more values than the original data
